name: Auto Deploy

on:
  push:
    branches: [ main ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: SSH and deploy chatbot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ssh_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/gcal-telegram/
            git checkout -- .
            git fetch
            git pull origin main
            npm install
            pm2 restart zelly-assistant
